language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libmp3lame-dev
