language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-19mode
  - jruby-18mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-18mode
    - rvm: jruby-head
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libmp3lame-dev
