language: ruby
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - rbx-2.2.7
  - ruby-head
  - jruby-19mode
  - jruby-18mode
  - jruby-head
before_install:
- sudo apt-get install -qq libmp3lame-dev
